---
- hosts: all
  user: gns3
  sudo: yes
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
    - name: Download Docker Script
      command: curl -fsSL https://get.docker.com -o get-docker.sh
    - name: Run Docker Script
      command: sh get-docker.sh
